### PR TITLE
Release/2.1

### PR DESCRIPTION
**Pull request by pippinsplugins**
Release 2.1 WIP

### CODE REVIEW

**Comment by tnorthcutt** [comment]
parks-rec-andy-excited

**Comment by mintplugins** [comment]
@tnorthcutt lol

@pippinsplugins great work!

**Comment by pippinsplugins** [comment]
Hehe.

**Comment by carter2422** [comment]
This is great!

**Comment by sumobi** [comment]
:+1: it's so close I can feel it

**Pull request merged**
