### PR TITLE
Submit through ajax instead of form submit

### PR DESCRIPTION
**Pull request by ahansson89**
Was thinking something along the lines of this #151

### CODE REVIEW

**Comment by ahansson89** [comment]
First of all it makes it easier to debug when you can get the ajax output of the process function. On the other hand it is nice because customers are not taken away from the payment page and therefore they do not need to re-enter their information if it is typed incorrectly.

**Comment by pippinsplugins** [comment]
@ahansson89 See my comment on #151 :)

**Comment by ahansson89** [comment]
Oh... Awesome!

**Comment by pippinsplugins** [comment]
:)

**Pull request closed without merging**
